# Docker Compose for Delivery Order Processing Center (DOPC) and Locust perfomance testing

services:
  dopc:
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./app:/code/app
      - ./tests:/code/tests
  locust:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./locustfile.py:/mnt/locust/locustfile.py
      - ./app:/mnt/locust/app
    command: -f /mnt/locust/locustfile.py --host http://dopc:8080
    depends_on:
      - dopc
